### PR TITLE
Merge upstream changes

### PR DESCRIPTION
**Pull request by scott-8**

### CODE REVIEW

**Comment by dan-v** [comment]
@scott-8 - are these changes still valid? if so, could you fix conflicts.

**Comment by scott-8** [comment]
I have not tested these changes, but they're just pulled directly from upstream. 

I don't see a conflict on my end (although I deleted the original repo so I may have to do another PR) but if I remember correctly there isn't actually a conflict it's just some weird spacing issue in strings.xml.

**Comment by dan-v** [comment]
@scott-8 - yeah, if you can fire up another PR that would be cool. sorry for the long delay on initial PR.

**Comment by scott-8** [comment]
moved to #6

**Pull request closed without merging**
